baseURL = 'https://bienensteff.de'
languageCode = 'de-de'
title = "Imkerei BienenSteff ğŸ"
enableRobotsTXT = "true"
timeZone = "Europe/Berlin"
enableEmoji = "true"
pluralizelisttitles = "false"

[params]
description = "Imkerei BienenSteff: Honig aus dem MÃ¼nchner GrÃ¼ngÃ¼rtel. Keep it simple."

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
# [[menus.main]]
#     name = 'News'
#     pageRef = '/blog'
#     weight = 20
[[menus.main]]
    name = 'Verkauf'
    pageRef = '/sale'
    weight = 30
[[menus.main]]
    name = 'Datenbank'
    pageRef = '/database'
    weight = 40
[[menus.main]]
    name = 'Werkzeuge'
    pageRef = '/tools'
    weight = 50
[[menus.main]]
    name = 'Ãœber uns'
    pageRef = '/about'
    weight = 60

[[menus.footer]]
    name = 'ğŸ”— Flaticon'
    URL = 'https://www.flaticon.com/free-icons/bee'
    weight = 10

[[menus.footer]]
    name = 'ğŸ”— Instagram'
    URL = 'https://www.instagram.com/bienensteff'
    weight = 20

[[menus.footer]]
    name = 'ğŸ”— Schwarmrettung'
    URL = 'https://schwarmrettung.de/'
    weight = 30

# [[menus.footer]]
#     name = 'ğŸ”— Kleinanzeigen'
#     URL = 'https://www.kleinanzeigen.de/s-bestandsliste.html?userId=138484447'
#     weight = 40
#
[[menus.footer]]
    name = 'Impressum'
    pageRef = '/impressum'
    weight = 50

[[menus.footer]]
    name = 'Datenschutz'
    pageRef = '/datenschutz'
    weight = 60

[imaging]
  quality = 97

  [markup.goldmark.renderer]
    unsafe = true

      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = 'â€'
        leftSingleQuote = 'â€š'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = 'â€'
        rightSingleQuote = 'â€˜'

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
