baseURL = 'https://bienensteff.de'
defaultContentLanguage = "de"
languageCode = 'de-DE'
title = "Imkerei Stefan Tatschner üêù"
timeZone = "Europe/Berlin"
enableEmoji = true
pluralizeListTitles = false
enableRobotsTXT = true
theme = "bienensteff"

[params]
description = "Honig und Bienen aus dem M√ºnchner Gr√ºng√ºrtel"
contact = """Imkerei Stefan Tatschner  
Gr√§felfinger Str. 169a  
81375 M√ºnchen

<i class="bi bi-telephone"></i> [+49 1512 4096409](tel:+4915124096409)  
<i class="bi bi-envelope"></i> info@bienensteff.de  
<i class="bi bi-instagram"></i> [@bienensteff](https://www.instagram.com/bienensteff)
"""

[menus]
  [[menus.main]]
  name = 'Verkauf'
  pageRef = '/verkauf'
  weight = 30

  [[menus.main]]
  name = 'Rezepte'
  pageRef = '/rezepte'
  weight = 40

  [[menus.main]]
  name = 'Honigkunde'
  pageRef = '/honigkunde'
  weight = 50

  [[menus.main]]
  name = 'Schw√§rme/Nester'
  pageRef = '/schwaerme-und-nester'
  weight = 60

  [[menus.main]]
  name = '√úber uns'
  pageRef = '/√ºber-uns'
  weight = 70

  [[menus.main]]
  name = 'Mehr'
  weight = 99

  [[menus.main]]
  name = 'Werkzeuge'
  parent = "Mehr"
  pageRef = '/werkzeuge'

  [[menus.main]]
  name = 'Datenbank'
  parent = "Mehr"
  pageRef = '/datenbank'

  [[menus.footerExternalLinks]]
  name = 'Schwarmrettung'
  pre = '<i class="bi bi-box-arrow-up-right"></i>'
  URL = 'https://schwarmrettung.de/'
  weight = 1

  [[menus.footerExternalLinks]]
  name = 'Flaticon'
  pre = '<i class="bi bi-box-arrow-up-right"></i>'
  URL = 'https://www.flaticon.com/free-icons/bee'
  weight = 2

  [[menus.footerExternalLinks]]
  name = 'Deutscher Imkerbund e.V.'
  pre = '<i class="bi bi-box-arrow-up-right"></i>'
  URL = 'https://deutscherimkerbund.de/'
  weight = 30

  [[menus.footerExternalLinks]]
  name = 'LV Bayerischer Imker e.V.'
  pre = '<i class="bi bi-box-arrow-up-right"></i>'
  URL = 'https://lvbi.de/'
  weight = 40

  [[menus.footerExternalLinks]]
  name = 'BZV M√ºnchen und Umgebung e.V.'
  pre = '<i class="bi bi-box-arrow-up-right"></i>'
  URL = 'https://bzvm.de/'
  weight = 60

  [[menus.footerLegal]]
  name = 'Impressum'
  pageRef = '/impressum'
  weight = 10

  [[menus.footerLegal]]
  name = 'Datenschutz'
  pageRef = '/datenschutz'
  weight = 20


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '‚Äû'
        leftSingleQuote = '‚Äö'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '‚Äù'
        rightSingleQuote = '‚Äò' 

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[imaging]
  quality = 97
  resampleFilter = "Lanczos"

[security]
  enableInlineShortcodes = true
